### ISSUE TITLE
some courses don't show up after clicking

### ISSUE THREAD

**Issue by khayyamsaleem** [danielheyman/stevens-scheduler#1]
This issue is more prevalent with the web courses, that aren't showing up in that custom box on the right. Example: CS545

**Comment by danielheyman** [comment]
@khayyamsaleem some classes don't appear if they're an alias or don't have an assigned time/day. Is CS545 the only one that's causing you an issue?

**Comment by khayyamsaleem** [comment]
It's just a few of the online classes. not a huge deal, but it seems to only be an issue for some online classes, which don't HAVE an assigned time/day.

**Comment by danielheyman** [comment]
Thanks I'll look into it

**Comment by danielheyman** [comment]
@khayyamsaleem fixed, thanks for the report 👍
